INSERT INTO CASH_CARD(ID, AMOUNT, OWNER)VALUES (99, 123.45, 'goku');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER)VALUES (100, 1.00, 'goku');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER)VALUES (101, 150, 'goku');